language: python
dist: xenial
sudo: required
python:
  - "3.5"
install:
  - src/installDependencies.sh
  - pip install psycopg2
# command to run tests
script:
  - tests/test.sh
  - src/runAll.sh
after_script:
  - cat src/config.json
  - cat export.csv
